In [2]:
#type: ignore
import torch 
from torch import nn
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Pytorch tensors are created using torch.tensor
scalar = torch.tensor(1)
scalar

tensor(1)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

1

In [6]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [7]:
# Dimensions = number of pair of square brakects 
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
MATRIX = torch.tensor([[7,7,7], [1,2,3]])
MATRIX

tensor([[7, 7, 7],
        [1, 2, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 3])

In [12]:
random_image = torch.rand(size=(3,244,244))


In [13]:
random_image.dtype

torch.float32

In [14]:
torch.arange(start=1, end= 10, step=2)

tensor([1, 3, 5, 7, 9])

In [15]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [16]:
T1 = torch.tensor([[1, 2], [4, 5], [7, 8]])
T2 = torch.tensor([[1, 2, 5], [ 4, 7,8]])
print(T1.shape)
print(T2.shape)
print(torch.matmul(T2, T1))
print(torch.matmul(T1, T2))

torch.Size([3, 2])
torch.Size([2, 3])
tensor([[ 44,  52],
        [ 88, 107]])
tensor([[ 9, 16, 21],
        [24, 43, 60],
        [39, 70, 99]])


In [17]:
print(T1)
print(T2.T)

tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([[1, 4],
        [2, 7],
        [5, 8]])


In [24]:
A = torch.arange(start=1, end=10)
print(A)
B = A.reshape((3, 3))
print(B)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [33]:
A.view(9)
B  = A.clone()
A, B
A[1]=0
A, B

(tensor([1, 0, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [49]:
z= torch.tensor([1,2,3,4,5,6,7,8])
m = torch.stack([z,z,z,z], dim=1)


[[[tensor([[1, 1, 1, 1],
           [2, 2, 2, 2],
           [3, 3, 3, 3],
           [4, 4, 4, 4],
           [5, 5, 5, 5],
           [6, 6, 6, 6],
           [7, 7, 7, 7],
           [8, 8, 8, 8]])]]]

In [52]:
m.unsqueeze(dim=1)

tensor([[[1, 1, 1, 1]],

        [[2, 2, 2, 2]],

        [[3, 3, 3, 3]],

        [[4, 4, 4, 4]],

        [[5, 5, 5, 5]],

        [[6, 6, 6, 6]],

        [[7, 7, 7, 7]],

        [[8, 8, 8, 8]]])

In [55]:
rando  = torch.rand((3,4,5))
print(rando)

tensor([[[0.5321, 0.6258, 0.6241, 0.6766, 0.3983],
         [0.0355, 0.7295, 0.3558, 0.5619, 0.5477],
         [0.1414, 0.9309, 0.8647, 0.5297, 0.1394],
         [0.4891, 0.7058, 0.3667, 0.3026, 0.8455]],

        [[0.9583, 0.6887, 0.3358, 0.3732, 0.9560],
         [0.8612, 0.7356, 0.2228, 0.1145, 0.6192],
         [0.9594, 0.6714, 0.7540, 0.7397, 0.7921],
         [0.2065, 0.1703, 0.4426, 0.1077, 0.8380]],

        [[0.8925, 0.0716, 0.9708, 0.2092, 0.5195],
         [0.9585, 0.8824, 0.4937, 0.8374, 0.3894],
         [0.6825, 0.6193, 0.4758, 0.2176, 0.8722],
         [0.8617, 0.7106, 0.7877, 0.4460, 0.9784]]])


In [56]:
rando.permute((2,1,0))

tensor([[[0.5321, 0.9583, 0.8925],
         [0.0355, 0.8612, 0.9585],
         [0.1414, 0.9594, 0.6825],
         [0.4891, 0.2065, 0.8617]],

        [[0.6258, 0.6887, 0.0716],
         [0.7295, 0.7356, 0.8824],
         [0.9309, 0.6714, 0.6193],
         [0.7058, 0.1703, 0.7106]],

        [[0.6241, 0.3358, 0.9708],
         [0.3558, 0.2228, 0.4937],
         [0.8647, 0.7540, 0.4758],
         [0.3667, 0.4426, 0.7877]],

        [[0.6766, 0.3732, 0.2092],
         [0.5619, 0.1145, 0.8374],
         [0.5297, 0.7397, 0.2176],
         [0.3026, 0.1077, 0.4460]],

        [[0.3983, 0.9560, 0.5195],
         [0.5477, 0.6192, 0.3894],
         [0.1394, 0.7921, 0.8722],
         [0.8455, 0.8380, 0.9784]]])

In [68]:
array = np.arange(start=2, stop=21, step=2)
tensor = torch.from_numpy(array)
tensor, array


(tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=torch.int32),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]))

In [70]:
me = tensor.to(torch.int64)
me.dtype

torch.int64

In [83]:
RANDOM_SEED = 69

torch.manual_seed(RANDOM_SEED)
A=torch.rand((3,3))
torch.manual_seed(RANDOM_SEED)
B=torch.rand((3,3))
print(A)
print(B)
A==B

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077],
        [0.0888, 0.2429, 0.7053]])
tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077],
        [0.0888, 0.2429, 0.7053]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [99]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [100]:
torch.cuda.device_count()

1

In [101]:

tensor = torch.tensor([1,2,3,4])
print(tensor, tensor.device)

tensor([1, 2, 3, 4]) cpu


In [102]:
tensor2 = torch.tensor([1,2,3,4])
print(tensor2, tensor2.device)

tensor([1, 2, 3, 4]) cpu


In [103]:
tensor_gpu = tensor.to(device=device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3, 4], device='cuda:0') cuda:0


In [107]:
tensor_cpu = tensor_gpu.cpu()
tensor_cpu.numpy()

array([1, 2, 3, 4], dtype=int64)